PROG=hello

debug:
	sunCC -g -library=stlport4 -xopenmp=noopt ${PROG}.c -o ${PROG}.exe

release:
	sunCC -g -library=stlport4 -xopenmp -fast ${PROG}.c -o ${PROG}.exe

run go: {PROG}.exe
	./${PROG}.exe

clean:
	rm -f ${PROG}.exe ${PROG}.o *~

{PROG}.exe: debug