PROG=for

debug:
	sunCC -g -library=stlport4 -xopenmp=noopt  ${PROG}.c -o ${PROG}.exe

release:
	sunCC -g -library=stlport4 -xopenmp -fast ${PROG}.c -o ${PROG}.exe

run go: ${PROG}.exe
	./${PROG}.exe

clean:
	rm -rf ${PROG}.exe ${PROG}.o *~ *.er

${PROG}.exe: debug
